### ISSUE TITLE
Githubの設定

### ISSUE THREAD

**Issue by yuta-ike** [KoukiNAGATA/sushi-chat#199]
- [x] mainに加えてdevelopブランチへの直プッシュも禁止にする
- [x] レポジトリのデフォルトブランチをmainからdevelopに変更する
間違って未検証の機能を`main`にマージしてしまうことを防ぐため。
mainにマージする機能を間違えて`develop`にマージする分には大きな問題にはならないので、デフォルト`develop`が良さそう

**Comment by KoukiNAGATA** [comment]
done.
