### ISSUE TITLE
Room, ChatItem, Stamp等の永続化データを扱うインターフェースを切る

### ISSUE THREAD

**Issue by TOMOFUMI-KONDO** [KoukiNAGATA/sushi-chat#282]
from #281 

現状、Room, ChatItem, Stamp等の管理がグローバル変数的なものを使ってオンメモリで行われていたり、postgresのclientのsdkを直接操作して行われていたりする。これではグローバル変数がどこでどう書き換えられているのか意識してコーディングをしなければいけなかったり、インフラの差し替え(オンメモリのものを共有DBに置き換える等)が困難であったりする。
なので、アプリケーションとインフラのレイヤーを分離し、アプリケーションレイヤからはインターフェースを通して具体的な永続化データの管理を行うようにしたい。

**Comment by TOMOFUMI-KONDO** [comment]
現在、[tomokon/server/rearchitecture-trying](https://github.com/KoukiNAGATA/sushi-chat/tree/tomokon/server/rearchitecture-trying)のブランチで「こんな風にしてみたらどうだろう」というコードを書いてみている。
このブランチでやっていることは大体以下の通り
- `ioServer.ts`に責務を持たせ過ぎず、コントローラとしての処理だけを行わせた
- コントローラから呼ばれるアプリケーションサービスの層(`service`配下)を作り、その中でモデルの操作や永続化の処理を行うようにした
- アプリケーションサービスで行う永続化の処理は、リポジトリのインターフェース(`domain`配下の`I*Repository.ts`)越しに行い、実際の処理はアプリケーションサービスにDIしたリポジトリ層にて行わせた

やってないことは以下の通り
- リポジトリ層の実装
  - Room, Stamp, ChatItemのリポジトリをシングルトンのクラスにし、オンメモリで行っている。つまり、ただインターフェースを切っただけで中身は変わっていない。
  - 元々`RoomClass`や`SaveChatItemClass`で行っていたChatItemやStampの永続化処理も行わないようになっている。これは、永続化処理はリポジトリ層がやるべきなのでそちらに移行すべきと考えており、リポジトリそうがまだ実装途中であるためである。

**Comment by TOMOFUMI-KONDO** [comment]
レイヤードアーキテクチャについてざっくりわかりそうな記事
https://qiita.com/kichion/items/aca19765cb16e7e65946

**Comment by yuta-ike** [comment]
@TOMOFUMI-KONDO 
自分で書いたコードやねんけど、`/domein/room/room.ts`内のglobalSocketをどうにかしたい気持ちがある。domainがフレームワークに依存してるのが気持ち悪いのでインタフェースでラップしたら良いのかな。

**Comment by TOMOFUMI-KONDO** [comment]
> @TOMOFUMI-KONDO
> 自分で書いたコードやねんけど、`/domein/room/room.ts`内のglobalSocketをどうにかしたい気持ちがある。domainがフレームワークに依存してるのが気持ち悪いのでインタフェースでラップしたら良いのかな。

同意です！インターフェースでラップするのもそうですけど、そもそもRoomClassに配信の処理を持たせるのは明らかに過剰な責務だと思うので、ApplicationServiceのクラス(RoomService.tsとか)で配信の処理は持たせていいんじゃないかと思ってます。

**Comment by yuta-ike** [comment]
> ApplicationServiceのクラス(RoomService.tsとか)で配信の処理は持たせていいんじゃないかと思ってます。

なるほど確かに。
今Repositoryの呼び出しはServiceが行なっているから、Service側に持つ方が自然かな。DBも配信（?）もビジネスロジックから見たら似た立ち位置（なのか？）っぽいので揃えた方が綺麗に感じた。

**Comment by TOMOFUMI-KONDO** [comment]
そうですねー。
Roomに配信するって言うメソッドをモデルに置くかどうかは迷いどころだと思う。モデルの振る舞いを全部サービス側に持ってっちゃうと今度はモデルがどんな振る舞いを持つオブジェクトなのか分かりづらくなってしまうと言う問題もあるので(俗に言うドメインモデル貧血症というやつ)。Interface切っていればモデルからDBとか配信とか扱うのもダメではないとは思うし。
まあ考え過ぎても先に進めないし、とりあえずどっちに置くか決めて進めてしまっていい気はする。

> DBも配信（?）もビジネスロジックから見たら似た立ち位置（なのか？）っぽいので揃えた方が綺麗に感じた。

これは俺も同意で、ロジックから見たらDBも配信も具体的な何かしらの実装が裏にあるけど、それを気にしないで使えるようにインターフェース越しに使うものっていう意味で近い気がする。

**Comment by yuta-ike** [comment]
> まあ考え過ぎても先に進めないし、とりあえずどっちに置くか決めて進めてしまっていい気はする。

賛成です。近藤さん的に良さそうな方を選んじゃってくださいw
気になったところはここくらいなので、このまま進めて大丈夫だと思います！

**Comment by yuta-ike** [comment]
リファクタありがとうございます〜〜

**Comment by TOMOFUMI-KONDO** [comment]
よかったです！
