### ISSUE TITLE
CIをGitHub Actionsで動かす

### ISSUE THREAD

**Issue by TOMOFUMI-KONDO** [KoukiNAGATA/sushi-chat#332]
CIの内容
- サーバーサイドのテスト
- Linterの実行
- formatterの実行(dry-run)

**Comment by KoukiNAGATA** [comment]
@TOMOFUMI-KONDO 
これ閉じていいやつ？

**Comment by TOMOFUMI-KONDO** [comment]
@KoukiNAGATA 
いいやつ！閉じる
