### ISSUE TITLE
ルーム関連作成/取得エンドポイントの実装

### ISSUE THREAD

**Issue by yuta-ike** [KoukiNAGATA/sushi-chat#351]
## やること
- [ ] `GET /room`
- [ ] `GET /room/{id}`
- [ ] `POST /room/{id}`

**Comment by Eri-0910** [comment]
#366 で　`POST /room/{id}`　は大枠実装済み

**Comment by Eri-0910** [comment]
`POST /room/{id}` じゃないような気がする
